version: "3"
services:
  dev:
    image: node:10
    volumes:
      - .:/app
      - .docker/node_modules:/app/node_modules
    working_dir: /app
    command: yarn dev
    ports:
      - 5678:5678
  pg:
    image: postgres:12
