version: "3"
services:
  dev:
    image: node:10
    environment:
      - FORCE_COLOR=2
    volumes:
      - .:/app
      - .docker/node_modules:/app/node_modules
    working_dir: /app
    command: yarn dev
    ports:
      - 5678:5678
  test:
    image: node:10
    environment:
      - FORCE_COLOR=2
    volumes:
      - .:/app
      - .docker/node_modules:/app/node_modules
    working_dir: /app
    command: yarn test:watch
  pg:
    image: postgres:11
    volumes:
      - .docker/postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M
