version: "2"
services:
  base:
    image: node:10
    volumes:
      - .:/app
      - .docker/node_modules:/app/node_modules
    working_dir: /app
  install:
    extends:
      service: base
    command: yarn
  setup:
    extends:
      service: base
    command: yarn setup docker
